# Generated by Django 3.0.7 on 2021-11-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
