# Generated by Django 3.0.7 on 2021-11-16 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0003_auto_20211116_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autos.Category'),
        ),
        migrations.AddField(
            model_name='auto',
            name='make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autos.Make'),
        ),
        migrations.AddField(
            model_name='auto',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autos.Model'),
        ),
        migrations.AddField(
            model_name='auto',
            name='trim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autos.Trim'),
        ),
    ]
