# Generated by Django 3.0.7 on 2021-11-16 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0004_auto_20211116_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autos.Make'),
        ),
        migrations.AddField(
            model_name='trim',
            name='make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autos.Make'),
        ),
        migrations.AddField(
            model_name='trim',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autos.Model'),
        ),
    ]
