# Generated by Django 3.1.7 on 2021-11-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0005_auto_20211116_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('dept', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
