# Generated by Django 3.1.7 on 2021-11-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0007_auto_20211119_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='engine',
            field=models.CharField(blank=True, choices=[('V6', 'V6'), ('V8', 'V8'), ('I6', 'I6'), ('ELECTRIC', 'ELECTRIC')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='auto',
            name='intcolor',
            field=models.CharField(blank=True, choices=[('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Silver', 'Silver'), ('Green', 'Green'), ('Black', 'Black')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='auto',
            name='transmission',
            field=models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=200, null=True),
        ),
    ]
