# Generated by Django 3.1.7 on 2021-11-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0008_auto_20211119_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='milage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
