# Generated by Django 3.1.7 on 2021-11-19 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autos', '0009_auto_milage'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured',
            name='auto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autos.auto'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autos.auto')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
