# Generated by Django 3.1.7 on 2021-11-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0010_auto_20211119_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
