# Generated by Django 3.1.7 on 2021-11-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0011_auto_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='auto',
            name='features',
            field=models.ManyToManyField(to='autos.Feature'),
        ),
    ]
