# Generated by Django 4.0.3 on 2022-03-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0013_auto_20211201_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
