# Generated by Django 4.0.3 on 2022-03-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0014_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Featured',
        ),
    ]
