# Generated by Django 4.0.3 on 2022-03-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0017_auto_rating_alter_order_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='plate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auto',
            name='vin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
