# Generated by Django 4.0.3 on 2022-04-08 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0019_auto_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='doors',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='fueltype',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='intcolor',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='milage',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='owners',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='plate',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='transmission',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='user',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='vin',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='year',
        ),
    ]
