# Generated by Django 4.0.3 on 2022-04-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0020_remove_auto_condition_remove_auto_doors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='discountpct',
            field=models.FloatField(default=0.0),
        ),
    ]
